spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-api-example
  template:
    metadata:
      labels:
        app: go-api-example
    spec:
      containers:
        - name: go-api-example-container
          image: lokinious/practice:latest
          ports:
            - containerPort: 8080
          env:
            - name: REDIS_ADDR
              value: "redis-service:6379"
